### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by domluna** [domluna/GloVe.jl#8]
This should have probably been the initial issue. Oh well :(

Overview of work to do:
- [x] Setup up CI workflow
- [ ] Make timings competitive with the C implementation
- [ ] Use all the cores
- [ ] Awesome notebook examples
